ARG REGISTRY_URL="docker.io/springcloud/"
ARG BASE_IMG_NAME="baseimage"
ARG BASE_IMG_VERS="1.0.0"
FROM ${REGISTRY_URL}${BASE_IMG_NAME}:${BASE_IMG_VERS}

ARG LANG_TERR="ko_KR"
ARG CODESET_U="UTF-8"
ARG CODESET_R="utf8"

ENV LANG ${LANG_TERR}.${CODESET_U}
ENV LANGUAGE ${LANG}
ENV LC_ALL ${LANG}

RUN apt-get update
RUN apt-get install -y locales tzdata

RUN locale-gen ${LC_ALL}
RUN localedef -f ${CODESET_U} -i ${LANG_TERR} "${LANG_TERR}.${CODESET_R}"
RUN update-locale LANG=${LC_ALL}
