## ======================================
## Embedded Tomcat Server Properties
## * Ref. https://docs.spring.io/spring-boot/docs/2.6.4/reference/htmlsingle/#application-properties.server
## ======================================
spring:
  application:
    name: day2app
server:
  port: 8082
  servlet:
    context-path: "/"
    encoding:
      charset: "UTF-8"
      enabled: true
      force: true
  tomcat:
    accept-count: 100
    max-connections: 100
    threads:
      max: 20
      min-spare: 20
management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}