## ======================================
## Embedded Tomcat Server Properties
## * Ref. https://docs.spring.io/spring-boot/docs/2.6.4/reference/htmlsingle/#application-properties.server
## ======================================
server:
  port: 8081
  servlet:
    context-path: "/"
    encoding:
      charset: "UTF-8"
      enabled: true
      force: true
  tomcat:
    accept-count: 100
    threads:
      max: 200
      min-spare: 100

## ===================================
## TODO: Spring Actuator
## * Ref. https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.endpoints.health.auto-configured-health-indicators
## ===================================
#management:
#  health:
#    defaults.enabled: false
#    livenessState.enabled: true
#    readinessState.enabled: true

## ======================================
## DATASOURCE & JPA & KAFKA
## * Ref. maximum-pool-size > https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing#connections--core_count--2--effective_spindle_count
## ======================================
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/day1
    username: postgres
    password: postgres1234
    connectionTestQuery: "SELECT 1"
    maximumPoolSize: 50
    minimumIdle: 50
  datasource-read-only:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/day1
    username: postgres
    password: postgres1234
    connectionTestQuery: "SELECT 1"
    maximumPoolSize: 50
    minimumIdle: 50
  jpa:
    database: "postgresql"
    hibernate:
      ddl-auto: validate # create disabled: schema has been managed by flyway on docker-compose
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        default_schema: "builder"
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
        format_sql: false
        show-sql:
        use_sql_comments: true
        use_jdbc_metadata_defaults: true

## ======================================
## Actuator
## * Ref. Production-ready Features > https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html
## ======================================
management:
  health:
    defaults:
      enabled: false
    db:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      show-components: always
      group:
        readiness:
          show-details: always
          include: "readinessState,db"
  metrics:
    tags:
      application: day1-builder

microservice:
  day2:
    url: "http://localhost:8082"