name: "Set local ACT envrionment"
description: "Server ACT environment for hack in local"

runs:
  using: composite
  steps:
  - name: 🏃 [ACT] Set hostname to acknowledge act container itself
    shell: bash
    run: echo "127.0.0.1   $(hostname)" | sudo tee -a /etc/hosts

  - name: 🏃 [ACT] Check 'node' exsits
    id: check-node-exist
    continue-on-error: true
    shell: bash
    run: node --version

  - if: ${{ steps.check-node-exist.outcome != 'success' }}
    name: 🏃 [ACT] Add nameserver to resolve
    shell: bash
    run: |
      echo "# Google IPv4 nameservers" | sudo tee -a /etc/resolv.conf
      echo "nameserver 8.8.8.8"        | sudo tee -a /etc/resolv.conf
      echo "nameserver 8.8.4.4"        | sudo tee -a /etc/resolv.conf

      echo "# Google IPv6 nameservers"       | sudo tee -a /etc/resolv.conf
      echo "nameserver 2001:4860:4860::8888" | sudo tee -a /etc/resolv.conf
      echo "nameserver 2001:4860:4860::8844" | sudo tee -a /etc/resolv.conf

      echo "# Pulbic DNS server" | sudo tee -a /etc/resolv.conf
      echo "nameserver 1.1.1.1"  | sudo tee -a /etc/resolv.conf

  - if: ${{ steps.check-node-exist.outcome != 'success' }}
    name: 🏃 [ACT] Install node to execute community actions
    shell: bash
    # Ref. https://github.com/nektos/act/issues/917#issuecomment-1074421318
    run: |
      echo "[1/3] Validate host"
      host deb.nodesource.com
      echo "(checked!)"

      echo "[2/3] Download nodejs source with setup"
      curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -  > /dev/null
      echcd o "(done)"

      echo "[3/3] Install nodejs with package manager"
      sudo apt-get install -qq -y nodejs
      echo "(finished)"

  - name: 🏃 [ACT] Set basic 'git' options
    shell: bash
    run: |
      git config --global init.defaultBranch main
