name: on-feature-pr-pushed
on:
  push:
    branches: [ 'main', 'haksung/*']

jobs:
  unit-test:
    runs-on: [ 'Linux', 'X64', 'HRA-control', 'dockered' ]
    steps:
      - name: my-step
        run: echo "Hello World!"